window.MUSIC_SERIES = [
  {
    "id": "midnight",
    "label": "午夜来信",
    "title": "午夜来信",
    "description": "从《不问来处》开始，把朋友的三首 AI 配乐，留在自己的书桌旁。",
    "recommendations": [
      {
        "id": "rec-affection",
        "title": "Affection",
        "artist": "Jinsang",
        "platform": "Bandcamp",
        "url": "https://jinsangbeats.bandcamp.com/track/affection"
      },
      {
        "id": "rec-aruarian-dance",
        "title": "Aruarian Dance",
        "artist": "Nujabes",
        "platform": "Apple Music",
        "url": "https://music.apple.com/us/song/1721843001"
      },
      {
        "id": "rec-both-of-us",
        "title": "Both of Us",
        "artist": "Idealism",
        "platform": "Spotify",
        "url": "https://open.spotify.com/track/1ADffIiBVfqDSRb8LKE3pU"
      }
    ]
  },
  {
    "id": "jazz",
    "label": "爵士乐",
    "title": "爵士小馆",
    "description": "小编制爵士、波萨与吉他小曲，给工作留一点松弛的律动。"
  },
  {
    "id": "lofi",
    "label": "Lo-fi",
    "title": "Lo-fi 书房",
    "description": "新增柔和的器乐 Lo-fi 与轻拍，也保留原来的电钢琴小曲。"
  },
  {
    "id": "chill",
    "label": "轻节奏",
    "title": "轻节奏 · 夜间电台",
    "description": "温暖电子音色与轻节奏，听一点有律动的旋律。"
  },
  {
    "id": "acoustic",
    "label": "原声乐",
    "title": "原声午后",
    "description": "拨弦吉他与温暖器乐，给午后添一点生气。"
  },
  {
    "id": "calm",
    "label": "轻音乐",
    "title": "轻音乐 · 钢琴与留白",
    "description": "柔和钢琴与轻器乐，也保留原来的四首安静长音。"
  }
];
window.CALM_TRACKS = [
  {
    "id": "lic-jazzrefill-lobby-time",
    "title": "Lobby Time",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与钢琴 · 休闲大厅",
    "src": "assets/lic-jazzrefill-lobby-time.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600054",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Lobby Time\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 193.125,
    "gain": 0.51584
  },
  {
    "id": "lic-jazzrefill-in-your-arms",
    "title": "In Your Arms",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "铜管与萨克斯 · 慢舞时光",
    "src": "assets/lic-jazzrefill-in-your-arms.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1500042",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"In Your Arms\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 168.673,
    "gain": 0.44692
  },
  {
    "id": "lic-jazzrefill-kool-kats",
    "title": "Kool Kats",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与吉他 · 松弛夜色",
    "src": "assets/lic-jazzrefill-kool-kats.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100601",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Kool Kats\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 200.708,
    "gain": 0.5
  },
  {
    "id": "lic-jazzrefill-intractable",
    "title": "Intractable",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "电钢琴与贝斯 · 轻放克爵士",
    "src": "assets/lic-jazzrefill-intractable.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100194",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Intractable\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 268.006,
    "gain": 0.5
  },
  {
    "id": "lic-jazzrefill-on-hold-for-you",
    "title": "On Hold for You",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "萨克斯音色与电钢琴 · 柔和电台",
    "src": "assets/lic-jazzrefill-on-hold-for-you.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN2000019",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"On Hold for You\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/ 制作说明：作者披露使用算法生成音符及和弦，并使用AI生成的次中音萨克斯演奏音色。",
    "duration": 218.087,
    "gain": 0.44611
  },
  {
    "id": "lic-jazzrefill-deadly-roulette",
    "title": "Deadly Roulette",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与贝斯 · 夜间轻律动",
    "src": "assets/lic-jazzrefill-deadly-roulette.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600033",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Deadly Roulette\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 159.231,
    "gain": 0.97131
  },
  {
    "id": "lic-jazzrefill-hard-boiled",
    "title": "Hard Boiled",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴三重奏 · 夜色小馆",
    "src": "assets/lic-jazzrefill-hard-boiled.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700076",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Hard Boiled\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 180.952,
    "gain": 0.84606
  },
  {
    "id": "lic-jazzrefill-bass-walker",
    "title": "Bass Walker",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "低音提琴独奏 · 缓步随行",
    "src": "assets/lic-jazzrefill-bass-walker.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1200071",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Bass Walker\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 161.482,
    "gain": 0.32223
  },
  {
    "id": "lic-lofirefill-dreamy-reverie",
    "title": "Dreamy Reverie",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "梦游般的轻拍 · Lo-fi",
    "src": "assets/lic-lofirefill-dreamy-reverie.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Dreamy Reverie\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 144.0,
    "gain": 0.50193,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-lofirefill-ease-into-night",
    "title": "Ease Into Night",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "夜间慢拍 · Lo-fi",
    "src": "assets/lic-lofirefill-ease-into-night.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Ease Into Night\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 151.899,
    "gain": 0.5,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-lofirefill-infinite-echoes",
    "title": "Infinite Echoes",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "柔和回响 · Lo-fi",
    "src": "assets/lic-lofirefill-infinite-echoes.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Infinite Echoes\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 140.308,
    "gain": 0.46804,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-lofirefill-into-the-mist",
    "title": "Into The Mist",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "薄雾轻拍 · Lo-fi",
    "src": "assets/lic-lofirefill-into-the-mist.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Into The Mist\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 129.6,
    "gain": 0.41647,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-lofirefill-lucid",
    "title": "Lucid",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "漂浮思绪 · Lo-fi",
    "src": "assets/lic-lofirefill-lucid.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Lucid\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 144.966,
    "gain": 0.33287,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-lofirefill-peaceful-drift",
    "title": "Peaceful Drift",
    "artist": "HoliznaCC0",
    "series": "lofi",
    "subtitle": "缓缓流动 · Lo-fi",
    "src": "assets/lic-lofirefill-peaceful-drift.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/public-domain-lo-fi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Peaceful Drift\" from \"Public Domain Lo-fi\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 128.333,
    "gain": 0.50854,
    "album": "Public Domain Lo-fi"
  },
  {
    "id": "lic-workrefill-avec-soin",
    "title": "Avec Soin",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "从容钢琴 · 安静收尾",
    "src": "assets/lic-workrefill-avec-soin.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100860",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Avec Soin\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 145.016,
    "gain": 0.50008
  },
  {
    "id": "lic-workrefill-facile",
    "title": "Facile",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "缓慢独奏 · 柔和钢琴",
    "src": "assets/lic-workrefill-facile.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100858",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Facile\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 212.0,
    "gain": 0.50002
  },
  {
    "id": "lic-workrefill-gymnopedie-no-1",
    "title": "Gymnopedie No. 1",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "萨蒂旋律 · 克制钢琴",
    "src": "assets/lic-workrefill-gymnopedie-no-1.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100787",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Gymnopedie No. 1\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/ Composition by Erik Satie; recording by Kevin MacLeod.",
    "duration": 187.013,
    "gain": 0.52182
  },
  {
    "id": "lic-workrefill-a-very-brady-special",
    "title": "A Very Brady Special",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "长篇钢琴 · 慢慢思考",
    "src": "assets/lic-workrefill-a-very-brady-special.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1900054",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"A Very Brady Special\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 388.246,
    "gain": 1.0
  },
  {
    "id": "lic-workrefill-laid-back-guitars",
    "title": "Laid Back Guitars",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "西班牙双吉他 · 松弛伴奏",
    "src": "assets/lic-workrefill-laid-back-guitars.mp3",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100181",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Laid Back Guitars\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 244.062,
    "gain": 0.47487
  },
  {
    "id": "lic-workrefill-windswept",
    "title": "Windswept",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他与弦乐 · 轻风拂过",
    "src": "assets/lic-workrefill-windswept.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100757",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Windswept\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 208.291,
    "gain": 0.50677
  },
  {
    "id": "lic-workrefill-fretless",
    "title": "Fretless",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他与尤克里里 · 晴朗午后",
    "src": "assets/lic-workrefill-fretless.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1500074",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Fretless\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 336.0,
    "gain": 0.50002
  },
  {
    "id": "lic-workrefill-sunshine",
    "title": "Sunshine",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "钢琴与节奏吉他 · 日光片刻",
    "src": "assets/lic-workrefill-sunshine.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100517",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Sunshine\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 201.818,
    "gain": 0.3661
  },
  {
    "id": "lic-workrefill-chill-wave",
    "title": "Chill Wave",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "柔和电子 · 吉他律动",
    "src": "assets/lic-workrefill-chill-wave.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600048",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Chill Wave\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 240.0,
    "gain": 0.34016
  },
  {
    "id": "lic-workrefill-dreamer",
    "title": "Dreamer",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "钢琴和弦 · 轻柔打击",
    "src": "assets/lic-workrefill-dreamer.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600043",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Dreamer\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 204.0,
    "gain": 0.595
  },
  {
    "id": "lic-workrefill-sincerely",
    "title": "Sincerely",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "缓拍合成器 · 从容律动",
    "src": "assets/lic-workrefill-sincerely.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1900016",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Sincerely\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 375.417,
    "gain": 0.3717
  },
  {
    "id": "lic-workrefill-eternity",
    "title": "Eternity",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "电钢与吉他 · 轻松律动",
    "src": "assets/lic-workrefill-eternity.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600031",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Eternity\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 198.0,
    "gain": 0.23137
  },
  {
    "id": "lic-jazzplus-backbay-lounge",
    "title": "Backbay Lounge",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与吉他 · 慢享小馆",
    "src": "assets/lic-jazzplus-backbay-lounge.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700068",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Backbay Lounge\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 266.5,
    "gain": 0.94957
  },
  {
    "id": "lic-jazzplus-casa-bossa-nova",
    "title": "Casa Bossa Nova",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "长笛与钢琴 · 波萨午后",
    "src": "assets/lic-jazzplus-casa-bossa-nova.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600012",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Casa Bossa Nova\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 242.069,
    "gain": 0.4924
  },
  {
    "id": "lic-jazzplus-ultralounge",
    "title": "Ultralounge",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与贝斯 · 松弛长篇",
    "src": "assets/lic-jazzplus-ultralounge.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1500017",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Ultralounge\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 316.8,
    "gain": 0.48899
  },
  {
    "id": "lic-jazzplus-poppers-prosecco",
    "title": "Poppers and Prosecco",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "长号与钢琴 · 七十拍慢摇",
    "src": "assets/lic-jazzplus-poppers-prosecco.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700014",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Poppers and Prosecco\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 193.714,
    "gain": 0.53188
  },
  {
    "id": "lic-jazzplus-past-sadness",
    "title": "Past Sadness",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "电钢琴与贝斯 · 柔软慢拍",
    "src": "assets/lic-jazzplus-past-sadness.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1900007",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Past Sadness\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 213.333,
    "gain": 1.0
  },
  {
    "id": "lic-jazzplus-local-forecast-slower",
    "title": "Local Forecast - Slower",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与长笛 · 慢版电台",
    "src": "assets/lic-jazzplus-local-forecast-slower.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1300011",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Local Forecast - Slower\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 199.481,
    "gain": 0.29144
  },
  {
    "id": "lic-jazzplus-sidewalk-shade-slower",
    "title": "Sidewalk Shade - slower",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与钢琴 · 慢行街角",
    "src": "assets/lic-jazzplus-sidewalk-shade-slower.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1200104",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Sidewalk Shade - slower\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 182.787,
    "gain": 0.5194
  },
  {
    "id": "lic-jazzplus-crinoline-dreams",
    "title": "Crinoline Dreams",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与弦乐 · 明亮留白",
    "src": "assets/lic-jazzplus-crinoline-dreams.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700073",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Crinoline Dreams\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 246.375,
    "gain": 0.80282
  },
  {
    "id": "lic-jazzplus-acid-trumpet",
    "title": "Acid Trumpet",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "弱音小号与电钢琴 · 夜色休闲",
    "src": "assets/lic-jazzplus-acid-trumpet.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100339",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Acid Trumpet\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 208.196,
    "gain": 0.67649
  },
  {
    "id": "lic-jazzplus-i-knew-a-guy",
    "title": "I Knew a Guy",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与贝斯 · 慢步夜行",
    "src": "assets/lic-jazzplus-i-knew-a-guy.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100199",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"I Knew a Guy\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 166.88,
    "gain": 0.56567
  },
  {
    "id": "lic-jazzplus-long-stroll",
    "title": "Long Stroll",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "刷鼓与铜管 · 悠悠散步",
    "src": "assets/lic-jazzplus-long-stroll.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100174",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Long Stroll\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 254.627,
    "gain": 0.74629
  },
  {
    "id": "lic-jazzplus-night-docks-piano",
    "title": "Night on the Docks - Piano",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "独奏电钢琴 · 码头夜色",
    "src": "assets/lic-jazzplus-night-docks-piano.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100135",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Night on the Docks - Piano\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 174.0,
    "gain": 1.0
  },
  {
    "id": "lic-jazzplus-walking-along",
    "title": "Walking Along",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "刷鼓与颤音琴 · 轻步随行",
    "src": "assets/lic-jazzplus-walking-along.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100020",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Walking Along\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 143.416,
    "gain": 0.59159
  },
  {
    "id": "lic-jazzplus-space-jazz",
    "title": "Space Jazz",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "合成器爵士 · 缓缓太空漫游",
    "src": "assets/lic-jazzplus-space-jazz.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN2100030",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Space Jazz\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 369.438,
    "gain": 0.8829
  },
  {
    "id": "lic-jazzother-busted-guitar-1",
    "title": "Track 1",
    "artist": "HoliznaCC0",
    "series": "jazz",
    "subtitle": "Busted Guitar · 松弛爵士吉他",
    "src": "assets/lic-jazzother-busted-guitar-1.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/busted-guitar-jazz",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Track 1\" from \"Busted Guitar (Jazz)\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 256.5,
    "gain": 0.3158,
    "album": "Busted Guitar (Jazz)"
  },
  {
    "id": "lic-jazzother-busted-guitar-2",
    "title": "Track 2",
    "artist": "HoliznaCC0",
    "series": "jazz",
    "subtitle": "Busted Guitar · 松弛爵士吉他",
    "src": "assets/lic-jazzother-busted-guitar-2.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/busted-guitar-jazz",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Track 2\" from \"Busted Guitar (Jazz)\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 162.188,
    "gain": 0.3427,
    "album": "Busted Guitar (Jazz)"
  },
  {
    "id": "lic-jazzother-busted-guitar-3",
    "title": "Track 3",
    "artist": "HoliznaCC0",
    "series": "jazz",
    "subtitle": "Busted Guitar · 松弛爵士吉他",
    "src": "assets/lic-jazzother-busted-guitar-3.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/busted-guitar-jazz",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Track 3\" from \"Busted Guitar (Jazz)\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 164.118,
    "gain": 0.29943,
    "album": "Busted Guitar (Jazz)"
  },
  {
    "id": "lic-jazzother-busted-guitar-4",
    "title": "Track 4",
    "artist": "HoliznaCC0",
    "series": "jazz",
    "subtitle": "Busted Guitar · 松弛爵士吉他",
    "src": "assets/lic-jazzother-busted-guitar-4.mp3",
    "sourceUrl": "https://holiznacc0.bandcamp.com/album/busted-guitar-jazz",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Track 4\" from \"Busted Guitar (Jazz)\" by HoliznaCC0 (holiznacc0.bandcamp.com). Licensed under Creative Commons Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 123.0,
    "gain": 0.29956,
    "album": "Busted Guitar (Jazz)"
  },
  {
    "id": "lic-jazz-jazz-brunch",
    "title": "Jazz Brunch",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "电钢琴与吉他 · 咖啡馆午后",
    "src": "assets/lic-jazz-jazz-brunch.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700074",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Jazz Brunch\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 323.05,
    "gain": 0.53145
  },
  {
    "id": "lic-jazz-study-relax",
    "title": "Study And Relax",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "萨克斯与钢琴 · 松弛慢拍",
    "src": "assets/lic-jazz-study-relax.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1900030",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Study And Relax\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 223.333,
    "gain": 0.81098
  },
  {
    "id": "lic-jazz-cool-vibes",
    "title": "Cool Vibes",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴三重奏 · 缓缓摇摆",
    "src": "assets/lic-jazz-cool-vibes.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100863",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Cool Vibes\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 218.313,
    "gain": 1.0
  },
  {
    "id": "lic-jazz-backed-vibes-clean",
    "title": "Backed Vibes (clean)",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与贝斯 · 干净轻巧",
    "src": "assets/lic-jazz-backed-vibes-clean.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100479",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Backed Vibes (clean)\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 228.35,
    "gain": 0.41401
  },
  {
    "id": "lic-jazz-bossa-antigua",
    "title": "Bossa Antigua",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "吉他与贝斯 · 轻柔波萨",
    "src": "assets/lic-jazz-bossa-antigua.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700069",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Bossa Antigua\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 283.286,
    "gain": 0.71049
  },
  {
    "id": "lic-jazz-bossa-bossa",
    "title": "BossaBossa",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "钢琴与吉他 · 波萨微风",
    "src": "assets/lic-jazz-bossa-bossa.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600055",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"BossaBossa\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 167.225,
    "gain": 0.5
  },
  {
    "id": "lic-jazz-vibing-venus",
    "title": "Vibing Over Venus",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "颤音琴与弦乐 · 松弛长篇",
    "src": "assets/lic-jazz-vibing-venus.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN2300005",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Vibing Over Venus\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 411.064,
    "gain": 0.74297
  },
  {
    "id": "lic-jazz-night-venice",
    "title": "Night in Venice",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "萨克斯与电钢琴 · 复古夜色",
    "src": "assets/lic-jazz-night-venice.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1900056",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Night in Venice\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 218.087,
    "gain": 0.33467
  },
  {
    "id": "lic-jazz-smooth-lovin",
    "title": "Smooth Lovin",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "吉他与风琴 · 慢速律动",
    "src": "assets/lic-jazz-smooth-lovin.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1700077",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Smooth Lovin\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 259.333,
    "gain": 1.0
  },
  {
    "id": "lic-jazz-groove-grove",
    "title": "Groove Grove",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "电钢琴与柔和节拍 · 轻轻铺底",
    "src": "assets/lic-jazz-groove-grove.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1200054",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Groove Grove\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 205.714,
    "gain": 0.27009
  },
  {
    "id": "lic-jazz-airport-lounge",
    "title": "Airport Lounge",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "电钢琴与颤音琴 · 轻盈候机厅",
    "src": "assets/lic-jazz-airport-lounge.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100806",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Airport Lounge\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 307.618,
    "gain": 0.51932
  },
  {
    "id": "lic-jazz-just-as-soon",
    "title": "Just As Soon",
    "artist": "Kevin MacLeod",
    "series": "jazz",
    "subtitle": "吉他与萨克斯 · 慢速六八拍",
    "src": "assets/lic-jazz-just-as-soon.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100185",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Just As Soon\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. https://creativecommons.org/licenses/by/4.0/",
    "duration": 228.034,
    "gain": 0.56618
  },
  {
    "id": "lic-chill-morning",
    "title": "Morning",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "古典吉他、竖琴与长笛 · 清晨轻奏",
    "src": "assets/lic-chill-morning.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN2300003",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Morning\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 153.253,
    "gain": 0.78421
  },
  {
    "id": "lic-chill-evening",
    "title": "Evening",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他、大提琴与双簧管 · 傍晚小品",
    "src": "assets/lic-chill-evening.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN2300002",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Evening\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 186.19,
    "gain": 0.45598
  },
  {
    "id": "lic-chill-almost-bliss",
    "title": "Almost Bliss",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "原声吉他与轻打击乐 · 松弛日常",
    "src": "assets/lic-chill-almost-bliss.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1900015",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Almost Bliss\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 316.5,
    "gain": 1.0
  },
  {
    "id": "lic-chill-midnight-tale",
    "title": "Midnight Tale",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他与鲁特琴 · 温暖木质音色",
    "src": "assets/lic-chill-midnight-tale.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1900004",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Midnight Tale\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 161.507,
    "gain": 0.51104
  },
  {
    "id": "lic-chill-clear-air",
    "title": "Clear Air",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "钢弦吉他、古典吉他与轻钢琴",
    "src": "assets/lic-chill-clear-air.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100626",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Clear Air\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 183.724,
    "gain": 0.50391
  },
  {
    "id": "lic-chill-somewhere-sunny",
    "title": "Somewhere Sunny (ver 2)",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "明亮干净的吉他二重奏",
    "src": "assets/lic-chill-somewhere-sunny.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100567",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Somewhere Sunny (ver 2)\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 114.655,
    "gain": 0.54262
  },
  {
    "id": "lic-chill-cattails",
    "title": "Cattails",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他、班卓琴与二胡 · 悠闲民谣",
    "src": "assets/lic-chill-cattails.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100743",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Cattails\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 158.961,
    "gain": 0.40354
  },
  {
    "id": "lic-chill-easy-lemon",
    "title": "Easy Lemon",
    "artist": "Kevin MacLeod",
    "series": "acoustic",
    "subtitle": "吉他、马林巴与轻节拍",
    "src": "assets/lic-chill-easy-lemon.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1200076",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Easy Lemon\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 126.311,
    "gain": 0.51576
  },
  {
    "id": "lic-chill-almost-new",
    "title": "Almost New",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "轻钢琴与低音弦乐 · 小小花园",
    "src": "assets/lic-chill-almost-new.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1800008",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Almost New\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 202.5,
    "gain": 1.0
  },
  {
    "id": "lic-chill-clear-waters",
    "title": "Clear Waters",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "简单轻盈的独奏钢琴",
    "src": "assets/lic-chill-clear-waters.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100290",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Clear Waters\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 128.038,
    "gain": 1.0
  },
  {
    "id": "lic-chill-midsummer-sky",
    "title": "Midsummer Sky",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "舒展明亮的独奏钢琴",
    "src": "assets/lic-chill-midsummer-sky.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100158",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Midsummer Sky\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 113.986,
    "gain": 1.0
  },
  {
    "id": "lic-chill-friday-morning",
    "title": "Friday Morning",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "平静、开阔的即兴钢琴",
    "src": "assets/lic-chill-friday-morning.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100224",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Friday Morning\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 210.234,
    "gain": 1.0
  },
  {
    "id": "lic-chill-winter-chimes",
    "title": "Winter Chimes",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "明亮钢琴 · 反复音型与对位",
    "src": "assets/lic-chill-winter-chimes.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100009",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Winter Chimes\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 158.067,
    "gain": 0.5
  },
  {
    "id": "lic-chill-there-is-romance",
    "title": "There is Romance",
    "artist": "Kevin MacLeod",
    "series": "calm",
    "subtitle": "慢速钢琴 · 温暖而清楚的旋律",
    "src": "assets/lic-chill-there-is-romance.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100044",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"There is Romance\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 197.593,
    "gain": 0.68656
  },
  {
    "id": "lic-chill-late-night-radio",
    "title": "Late Night Radio",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "电钢琴与低音 · 松弛慢节奏",
    "src": "assets/lic-chill-late-night-radio.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN2100003",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Late Night Radio\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 263.542,
    "gain": 0.37787
  },
  {
    "id": "lic-chill-dream-culture",
    "title": "Dream Culture",
    "artist": "Kevin MacLeod",
    "series": "chill",
    "subtitle": "朦胧钢琴与轻打击乐 · 轻盈节奏",
    "src": "assets/lic-chill-dream-culture.m4a",
    "sourceUrl": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1300046",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "attribution": "\"Dream Culture\" Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0. https://creativecommons.org/licenses/by/4.0/",
    "duration": 214.286,
    "gain": 0.54853
  },
  {
    "id": "jazz-window",
    "title": "窗边拿铁",
    "subtitle": "摇摆钢琴 · 拨弦低音 · 轻钹",
    "series": "jazz",
    "bpm": 78,
    "src": "assets/jazz-window.m4a",
    "duration": 147.69230769230768,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "jazz-lamp",
    "title": "夜灯三重奏",
    "subtitle": "电钢琴 · 小调慢摇摆 · 拨弦低音",
    "series": "jazz",
    "bpm": 72,
    "src": "assets/jazz-lamp.m4a",
    "duration": 160.0,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "lofi-pencil",
    "title": "铅笔沙沙",
    "subtitle": "松弛电钢 · 一点点律动",
    "series": "lofi",
    "bpm": 74,
    "src": "assets/lofi-pencil.m4a",
    "duration": 142.702703,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "lofi-late",
    "title": "晚一点也好",
    "subtitle": "夜色琴音 · 慢拍陪伴",
    "series": "lofi",
    "bpm": 72,
    "src": "assets/lofi-late.m4a",
    "duration": 146.666667,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "acoustic-leaves",
    "title": "树影翻页",
    "subtitle": "尼龙指弹 · 轻轻起伏",
    "series": "acoustic",
    "bpm": 80,
    "src": "assets/acoustic-leaves.m4a",
    "duration": 144,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "acoustic-sun",
    "title": "午后散步",
    "subtitle": "钢弦吉他 · 轻快不着急",
    "series": "acoustic",
    "bpm": 84,
    "src": "assets/acoustic-sun.m4a",
    "duration": 137.142857143,
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "mist",
    "title": "雾中留白",
    "subtitle": "空气和弦 · 缓慢铺底",
    "color": "#829a94",
    "src": "assets/mist.m4a",
    "duration": 156,
    "series": "calm",
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "paper",
    "title": "纸上微光",
    "subtitle": "柔软毡琴 · 稀疏长尾",
    "color": "#a99b75",
    "src": "assets/paper.m4a",
    "duration": 156,
    "series": "calm",
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "linen",
    "title": "亚麻午后",
    "subtitle": "木质泛音 · 柔和长尾",
    "color": "#b7977e",
    "src": "assets/linen.m4a",
    "duration": 156,
    "series": "calm",
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "night",
    "title": "深夜长页",
    "subtitle": "温暖长音 · 缓慢和声",
    "color": "#77829d",
    "src": "assets/night.m4a",
    "duration": 156,
    "series": "calm",
    "artist": "慢慢书桌原创",
    "gain": 1
  },
  {
    "id": "echo-public-night",
    "title": "不问来处",
    "artist": "echo-hall · MiniMax AI 配乐",
    "series": "midnight",
    "subtitle": "朋友的电台 · 本地完整曲目",
    "src": "assets/echo-public-night.mp3",
    "sourceUrl": "https://github.com/slzcn/echo-hall/blob/HEAD/js/config.js#L109",
    "attribution": "《不问来处》来自 slzcn/echo-hall 的公开 BGM。网站配置及原文件元数据标注 MiniMax 生成。保留原始 MP3，无裁剪；仅在播放时调整音量。收录自网站公开音频；未查到该音频的独立开放再分发许可。",
    "duration": 105.5,
    "gain": 0.32485
  },
  {
    "id": "echo-public-dawn",
    "title": "睡到自然醒",
    "artist": "echo-hall · MiniMax AI 配乐",
    "series": "midnight",
    "subtitle": "朋友的电台 · 本地完整曲目",
    "src": "assets/echo-public-dawn.mp3",
    "sourceUrl": "https://github.com/slzcn/echo-hall/blob/HEAD/js/config.js#L109",
    "attribution": "《睡到自然醒》来自 slzcn/echo-hall 的公开 BGM。网站配置及原文件元数据标注 MiniMax 生成。保留原始 MP3，无裁剪；仅在播放时调整音量。收录自网站公开音频；未查到该音频的独立开放再分发许可。",
    "duration": 158.163,
    "gain": 0.5
  },
  {
    "id": "echo-public-glow",
    "title": "慵懒午后",
    "artist": "echo-hall · MiniMax AI 配乐",
    "series": "midnight",
    "subtitle": "朋友的电台 · 本地完整曲目",
    "src": "assets/echo-public-glow.mp3",
    "sourceUrl": "https://github.com/slzcn/echo-hall/blob/HEAD/js/config.js#L109",
    "attribution": "《慵懒午后》来自 slzcn/echo-hall 的公开 BGM。网站配置及原文件元数据标注 MiniMax 生成。保留原始 MP3，无裁剪；仅在播放时调整音量。收录自网站公开音频；未查到该音频的独立开放再分发许可。",
    "duration": 209.63,
    "gain": 0.5
  }
];
