export default String.raw`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>慢慢书桌 · 使用概览</title>
<style nonce="__NONCE__">
:root{color-scheme:light;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;color:#343e38;background:#f6f5ef}*{box-sizing:border-box}body{margin:0}main{max-width:1050px;margin:50px auto;padding:0 24px 60px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-family:Georgia,"Songti SC",serif;font-size:32px;letter-spacing:2px;margin:8px 0}h2{font-size:17px;margin:0 0 18px;font-weight:550}.eyebrow{font-size:11px;letter-spacing:3px;color:#718071}.note,small{color:#718071;font-size:13px;line-height:1.8}button,select,input{font:inherit;border:1px solid #cdd4c9;border-radius:9px;padding:10px 13px;background:#fff;color:inherit}button{cursor:pointer}button.primary{background:#476652;color:white;border-color:#476652}input{width:100%;margin:12px 0}button:disabled{opacity:.6;cursor:wait}#login{max-width:410px;margin:80px auto;padding:28px;background:#fff;border:1px solid #e3e6dd;border-radius:18px}.controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:30px 0 20px}.controls input{width:auto;margin:0}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:#fff;border:1px solid #e1e5dc;border-radius:14px;padding:22px}.value{font-size:34px;margin-top:12px;font-variant-numeric:tabular-nums}.grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px;margin-top:18px}.panel{margin-top:18px;overflow:auto}.grid .panel{margin-top:0}table{width:100%;border-collapse:collapse;font-size:13px;white-space:nowrap;text-align:left}th{font-weight:500;color:#758174}td,th{padding:12px 10px;border-bottom:1px solid #eff1eb}td:first-child,th:first-child{padding-left:0}.bar{display:inline-block;height:7px;border-radius:4px;background:#a9b7a2;margin-left:10px;vertical-align:middle;max-width:120px}#status{min-height:24px;font-size:13px;color:#806047}#login-status{color:#975947;font-size:13px}.badge{display:inline-block;border-radius:6px;background:#ede8d5;color:#795f36;padding:4px 8px}#logout{font-size:13px;background:transparent}[hidden]{display:none!important}@media(max-width:640px){main{margin-top:28px;padding:0 18px 40px}h1{font-size:27px}.cards{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.card,.panel{padding:17px}.value{font-size:29px}#login{margin-top:40px}.controls{gap:10px}}
</style><main><header><div><div class="eyebrow">SLOW DESK · PRIVATE</div><h1>书桌上的回响</h1><p class="note">慢慢书桌 · 使用概览</p></div><button id="logout" hidden>退出登录</button></header>
<form id="login"><h2>打开你的统计页</h2><label for="key" class="note">管理员登录密钥</label><input id="key" type="password" autocomplete="current-password" required maxlength="256" placeholder="粘贴保存在本机的登录密钥"><button class="primary" id="enter">登录</button><p id="login-status" role="status"></p><small>登录有效期 8 小时。请保管好密钥，不要转发给朋友。</small></form>
<section id="dashboard" hidden><div class="controls"><select id="days" aria-label="统计日期范围"><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select><label class="note"><input id="test" type="checkbox"> 只看测试数据</label><button id="refresh">刷新</button><span id="mode" class="badge">真实数据</span></div><p id="status" role="status"></p>
<div class="cards"><div class="card"><small>打开次数</small><div class="value" id="opens">—</div></div><div class="card"><small>匿名访客数</small><div class="value" id="visitors">—</div></div><div class="card"><small>开始播放</small><div class="value" id="plays">—</div></div><div class="card"><small>听满 30 秒</small><div class="value" id="listens">—</div></div></div>
<div class="panel"><h2>每日使用</h2><table><thead><tr><th>日期</th><th>打开</th><th>访客</th><th>播放</th><th>满 30 秒</th></tr></thead><tbody id="daily"></tbody></table></div>
<div class="grid"><div class="panel"><h2>大家在听什么</h2><table><thead><tr><th>歌曲</th><th>播放</th><th>满 30 秒</th></tr></thead><tbody id="tracks"></tbody></table></div><div class="panel"><h2>从哪里来</h2><table><thead><tr><th>来源</th><th>打开</th></tr></thead><tbody id="sources"></tbody></table></div></div>
<div class="panel"><h2>最近记录</h2><table><thead><tr><th>时间（北京时间）</th><th>行为</th><th>歌曲</th><th>匿名编号</th></tr></thead><tbody id="recent"></tbody></table></div>
<p class="note">匿名访客按浏览器编号去重，不代表真实人数；不能识别具体朋友。播放排行受默认歌曲影响。只记录音乐播放，暂不统计自然声、总收听时长或实时在线。来源取决于分享链接标记，普通微信打开也可能显示为直接访问。记录保留 62 天，每日最多 1,000 条；网络失败、主动关闭统计或超出限额可能漏记。</p></section></main>
<script nonce="__NONCE__">
const $=id=>document.getElementById(id);
const names={page_view:'打开网页',play_start:'开始播放',listen_30s:'听满 30 秒',direct:'直接访问',share:'分享链接',wechat:'微信标记链接',friend:'朋友标记链接'};
let loading=false;
function row(id,values){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td)}$(id).append(tr)}
function empty(id,n){if(!$(id).children.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=n;td.textContent='这个时间段暂无记录';tr.append(td);$(id).append(tr)}}
function showLogin(){ $('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;for(const id of ['daily','tracks','sources','recent'])$(id).replaceChildren();for(const id of ['opens','visitors','plays','listens'])$(id).textContent='—';}
async function load(){if(loading)return;loading=true;$('refresh').disabled=true;$('days').disabled=true;$('test').disabled=true;try{
const r=await fetch('/api/stats?days='+$('days').value+'&test='+($('test').checked?'1':'0'),{cache:'no-store'});
if(r.status===401){showLogin();return}if(!r.ok)throw Error('暂时无法读取统计，请稍后刷新。');const d=await r.json();
$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('mode').textContent=d.test?'测试数据 · 不计入真实统计':'真实数据';
for(const id of ['opens','visitors','plays','listens'])$(id).textContent=(d.summary[id]||0).toLocaleString();
for(const id of ['daily','tracks','sources','recent'])$(id).replaceChildren();
for(const x of d.daily)row('daily',[x.day,x.opens,x.visitors,x.plays,x.listens]);
for(const x of d.tracks)row('tracks',[x.track_title,x.plays,x.listens]);
for(const x of d.sources)row('sources',[names[x.source]||x.source,x.opens]);
for(const x of d.recent)row('recent',[new Date(x.occurred_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}),names[x.event],x.track_title||'—',x.visitor_id.slice(0,8)]);
empty('daily',5);empty('tracks',3);empty('sources',2);empty('recent',4);$('status').textContent='更新于 '+new Date(d.generated_at).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' · 北京时间';
}catch(e){$('status').textContent=e.message;$('login-status').textContent=e.message;}finally{loading=false;$('refresh').disabled=false;$('days').disabled=false;$('test').disabled=false;}}
$('login').addEventListener('submit',async e=>{e.preventDefault();$('enter').disabled=true;$('login-status').textContent='正在登录…';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:$('key').value})});$('key').value='';if(!r.ok)throw Error(r.status===401?'密钥不正确，请重试。':'登录暂时不可用，请稍后重试。');$('login-status').textContent='';await load();}catch(e){$('login-status').textContent=e.message}finally{$('enter').disabled=false}});
$('logout').addEventListener('click',async()=>{try{const r=await fetch('/api/logout',{method:'POST'});if(!r.ok)throw Error();showLogin()}catch{$('status').textContent='退出失败，请检查网络后重试。'}});
for(const id of ['days','test'])$(id).addEventListener('change',load);$('refresh').addEventListener('click',load);load();
</script></html>`;
