import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import worker,{validate,insertSql} from './worker.mjs';
import catalogue from './catalogue.mjs';
const host='https://collector.example';
const event=(extra={})=>({version:1,event_id:randomUUID(),event:'page_view',occurred_at:new Date().toISOString(),visitor_id:randomUUID(),session_id:randomUUID(),source:'direct',track_id:'',track_title:'',series_id:'',...extra});
const request=(body,headers={})=>new Request(host+'/collect',{method:'POST',headers:{Origin:'https://61-design.github.io','Content-Type':'application/json',...headers},body:JSON.stringify(body)});
function setup(t){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));t.after(()=>sqlite.close());
 const DB={prepare(sql){const statement=sqlite.prepare(sql);const make=(args=[])=>({bind(...args){return make(args)},async run(){return {meta:{changes:statement.run(...args).changes}}},async first(){return statement.get(...args)??null},async all(){return {results:statement.all(...args)}}});return make()},async batch(statements){return Promise.all(statements.map(s=>s.all()))}};
 return {sqlite,env:{DB,DAILY_EVENT_CAP:'1000',TEST_DATA:'true',ADMIN_KEY:'test-only-'+randomUUID()+randomUUID()}};
}
async function login(env,key=env.ADMIN_KEY,origin=host){return worker.fetch(new Request(host+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({key})}),env)}
async function stats(env,cookie='',suffix=''){return worker.fetch(new Request(host+'/api/stats'+suffix,{headers:{Cookie:cookie}}),env)}
test('valid catalogue and exact anonymous schema',()=>{for(const [id,x] of Object.entries(catalogue)) assert.ok(validate(event({event:'play_start',track_id:id,track_title:x.title,series_id:x.series}),Date.now()));for(const patch of [{notes:'private'},{event:'bad'},{source:'https://private.example'},{visitor_id:'name'},{occurred_at:'2020-01-01'},{track_title:'unexpected'},{event:'play_start',track_id:'missing'}])assert.equal(validate(event(patch),Date.now()),null)});
test('disabled config, bad origins, oversized and private payload never write',async t=>{const {env,sqlite}=setup(t);for(const [req,status] of [[request(event(),{Origin:'https://evil.example'}),403],[request(event({notes:'private'})),400],[request(event({track_title:'x'.repeat(3000)})),400],[request(event(),{'Content-Type':'text/plain'}),415]])assert.equal((await worker.fetch(req,env)).status,status);env.DAILY_EVENT_CAP='0';assert.equal((await worker.fetch(request(event()),env)).status,503);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM events').get().n,0)});
test('preflight only permits approved origin without credentials',async()=>{const r=await worker.fetch(new Request(host+'/collect',{method:'OPTIONS',headers:{Origin:'https://61-design.github.io'}}),{});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://61-design.github.io');assert.equal(r.headers.get('Access-Control-Allow-Credentials'),null)});
test('concurrent duplicates create one durable event and no external request',async t=>{const {env,sqlite}=setup(t);t.mock.method(globalThis,'fetch',()=>{throw Error('no third-party requests')});const body=event();const responses=await Promise.all(Array.from({length:8},()=>worker.fetch(request(body),env)));assert.equal(responses.filter(x=>x.status===201).length,1);assert.equal(responses.filter(x=>x.status===409).length,7);const row=sqlite.prepare('SELECT * FROM events').get();assert.equal(row.event_id,body.event_id);assert.equal(row.test_data,1);assert.equal(row.occurred_at,Date.parse(body.occurred_at));assert.equal(Object.keys(row).length,11)});
test('daily quota fails closed even with concurrent requests',async t=>{const {env,sqlite}=setup(t);env.DAILY_EVENT_CAP='2';const responses=await Promise.all(Array.from({length:5},()=>worker.fetch(request(event()),env)));assert.equal(responses.filter(x=>x.status===201).length,2);assert.equal(responses.filter(x=>x.status===429).length,3);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM events').get().n,2)});
test('atomic SQL enforces second, minute and daily reset',t=>{const {sqlite}=setup(t);const stmt=sqlite.prepare(insertSql);function add(at,start=0,cap=100){return stmt.run(randomUUID(),'page_view',at,at,randomUUID(),randomUUID(),'direct','','','',1,start,cap,at-1000,at-60000).changes}for(let i=0;i<30;i++)assert.equal(add(1000000+Math.floor(i/5)*1500),1);assert.equal(add(1007600),0);assert.equal(add(1061000),1);assert.equal(add(1100000,1100000,1),1);assert.equal(add(1100001,1100000,1),0)});
test('stats are private; login rejects wrong keys and cross-site requests',async t=>{const {env}=setup(t);assert.equal((await stats(env)).status,401);assert.equal((await stats(env,'__Host-desk_session='+Date.now()+'.'+'a'.repeat(64))).status,401);assert.equal((await login(env,'wrong')).status,401);assert.equal((await login(env,env.ADMIN_KEY,'https://evil.example')).status,403);const r=await login(env);assert.equal(r.status,204);assert.match(r.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Strict/);assert.equal((await stats(env,r.headers.get('Set-Cookie').split(';')[0])).status,200)});
test('real stats exclude tests; visitors deduplicate and songs/sources aggregate',async t=>{const {env}=setup(t);const [id,track]=Object.entries(catalogue)[0];const visitor=randomUUID();await worker.fetch(request(event()),env);env.TEST_DATA='false';for(const body of [event({visitor_id:visitor}),event({visitor_id:visitor,source:'friend'}),event({visitor_id:visitor,event:'play_start',track_id:id,track_title:track.title,series_id:track.series}),event({visitor_id:visitor,event:'listen_30s',track_id:id,track_title:track.title,series_id:track.series})])assert.equal((await worker.fetch(request(body),env)).status,201);const cookie=(await login(env)).headers.get('Set-Cookie').split(';')[0];const real=await (await stats(env,cookie)).json();assert.deepEqual(real.summary,{opens:2,visitors:1,plays:1,listens:1});assert.equal(real.tracks[0].track_title,track.title);assert.equal(real.daily.length,1);assert.equal(real.recent.length,4);assert.equal((await (await stats(env,cookie,'?test=1')).json()).summary.opens,1);assert.equal((await stats(env,cookie,'?days=999')).status,400)});
test('logout expires browser cookie; rotating key revokes old sessions',async t=>{const {env}=setup(t);const cookie=(await login(env)).headers.get('Set-Cookie').split(';')[0];const r=await worker.fetch(new Request(host+'/api/logout',{method:'POST',headers:{Origin:host}}),env);assert.match(r.headers.get('Set-Cookie'),/Max-Age=0/);env.ADMIN_KEY='new-key-'+randomUUID();assert.equal((await stats(env,cookie)).status,401)});
test('admin shell contains no data or secret and has strict CSP',async t=>{const {env}=setup(t);const r=await worker.fetch(new Request(host+'/admin'),env);assert.equal(r.status,200);assert.match(r.headers.get('Content-Security-Policy'),/default-src 'none'/);assert.match(r.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);const html=await r.text();assert.ok(!html.includes(env.ADMIN_KEY));assert.ok(!html.includes('__NONCE__'));assert.match(html,/td.textContent=value/)});
test('scheduled retention removes only records older than 62 days',async t=>{const {env,sqlite}=setup(t);await worker.fetch(request(event()),env);const id=sqlite.prepare('SELECT event_id FROM events').get().event_id;sqlite.prepare('UPDATE events SET received_at=? WHERE event_id=?').run(Date.now()-63*86400000,id);await worker.fetch(request(event()),env);await worker.scheduled(null,env);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM events').get().n,1)});
